name: Run Python Script

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

# Define jobs
jobs:
  run-python:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies (if you have a requirements.txt file)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
